/**
 * 프로젝트 상세 페이지의 Mock 데이터
 */

import type {
  ProjectWithRelations,
  ProjectDocument,
  DocumentApproval,
  ActivityLog,
  Client,
  User,
} from '@/lib/domain/types';

// ── 사용자 ───────────────────────────────────────────────

export const MOCK_USERS: Record<string, User> = {
  u1: {
    id: 'u1',
    organization_id: 'org1',
    auth_id: 'auth-u1',
    email: 'kim@kka.co.kr',
    name: '김민수',
    role: 'manager',
    is_active: true,
    created_at: '2026-01-10T09:00:00Z',
    updated_at: '2026-03-01T09:00:00Z',
  },
  u2: {
    id: 'u2',
    organization_id: 'org1',
    auth_id: 'auth-u2',
    email: 'lee@kka.co.kr',
    name: '이지현',
    role: 'member',
    is_active: true,
    created_at: '2026-02-01T09:00:00Z',
    updated_at: '2026-03-15T09:00:00Z',
  },
  u3: {
    id: 'u3',
    organization_id: 'org1',
    auth_id: 'auth-u3',
    email: 'park@kka.co.kr',
    name: '박대표',
    role: 'admin',
    is_active: true,
    created_at: '2026-01-05T09:00:00Z',
    updated_at: '2026-03-20T09:00:00Z',
  },
};

// ── 고객사 ───────────────────────────────────────────────

export const MOCK_CLIENT: Client = {
  id: 'c1',
  organization_id: 'org1',
  name: '(주)블루오션 마케팅',
  contact_name: '정하린',
  contact_email: 'harin@blueocean.co.kr',
  contact_phone: '010-1234-5678',
  address: '서울특별시 강남구 테헤란로 152',
  notes: '장기 계약 고객사. 인스타그램 + 네이버 블로그 대행.',
  service_type: 'viral_performance',
  payment_type: 'deposit',
  tier: 'loyal',
  metadata: {},
  is_active: true,
  created_at: '2026-01-15T09:00:00Z',
  updated_at: '2026-03-01T09:00:00Z',
};

// ── 문서 ─────────────────────────────────────────────────

export const MOCK_DOCUMENTS: ProjectDocument[] = [
  {
    id: 'doc1',
    project_id: 'p1',
    type: 'estimate',
    status: 'sent',
    version: 1,
    title: '2026년 3월 마케팅 대행 견적서',
    content: {
      items: [
        { name: '인스타그램 피드 콘텐츠 (10건)', quantity: 10, unit_price: 150000, amount: 1500000 },
        { name: '네이버 블로그 포스팅 (8건)', quantity: 8, unit_price: 200000, amount: 1600000 },
        { name: '광고 대행 수수료', quantity: 1, unit_price: 500000, amount: 500000 },
      ],
      subtotal: 3600000,
      tax: 360000,
      total: 3960000,
      notes: 'VAT 별도. 추가 건수 발생 시 별도 협의.',
    },
    is_sent: true,
    sent_at: '2026-03-05T14:30:00Z',
    sent_by: 'u1',
    sent_to: 'harin@blueocean.co.kr',
    created_by: 'u2',
    metadata: {},
    created_at: '2026-03-03T10:00:00Z',
    updated_at: '2026-03-05T14:30:00Z',
  },
  {
    id: 'doc2',
    project_id: 'p1',
    type: 'contract',
    status: 'approved',
    version: 1,
    title: '블루오션 마케팅 대행 계약서',
    content: {
      terms: '계약 기간: 2026년 3월 ~ 5월 (3개월)',
      contract_date: '2026-03-10',
      effective_date: '2026-03-15',
      expiry_date: '2026-05-31',
    },
    is_sent: false,
    sent_at: null,
    sent_by: null,
    sent_to: null,
    created_by: 'u2',
    metadata: {},
    created_at: '2026-03-08T11:00:00Z',
    updated_at: '2026-03-12T09:15:00Z',
  },
  {
    id: 'doc3',
    project_id: 'p1',
    type: 'pre_report',
    status: 'in_review',
    version: 2,
    title: '3월 인스타그램 바이럴 마케팅 사전 보고서',
    content: {
      platform: 'Instagram',
      objective: '브랜드 인지도 향상',
      budget: 2000000,
      schedule_start: '2026-03-20',
      schedule_end: '2026-04-20',
      target_audience: '25~35세 여성, 뷰티/라이프스타일 관심층',
    },
    is_sent: false,
    sent_at: null,
    sent_by: null,
    sent_to: null,
    created_by: 'u2',
    metadata: {},
    created_at: '2026-03-15T13:00:00Z',
    updated_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'doc4',
    project_id: 'p1',
    type: 'pre_report',
    status: 'draft',
    version: 1,
    title: '3월 캠페인 중간 보고서',
    content: {
      period_start: '2026-03-20',
      period_end: '2026-03-30',
      summary: '인스타그램 릴스 3건 제작 완료, 블로그 4건 발행 완료',
    },
    is_sent: false,
    sent_at: null,
    sent_by: null,
    sent_to: null,
    created_by: 'u2',
    metadata: {},
    created_at: '2026-03-28T09:00:00Z',
    updated_at: '2026-03-28T09:00:00Z',
  },
];

// ── 승인 이력 ────────────────────────────────────────────

export const MOCK_APPROVALS: DocumentApproval[] = [
  // doc1 (견적서) - 2단계 승인 완료
  {
    id: 'ap1',
    document_id: 'doc1',
    requested_by: 'u2',
    requested_at: '2026-03-04T09:00:00Z',
    approver_id: 'u1',
    action: 'approve',
    actioned_at: '2026-03-04T14:00:00Z',
    step: 1,
    comment: null,
    metadata: { required_steps: 2, step_label: '담당자 승인', step_role: 'manager' },
    created_at: '2026-03-04T09:00:00Z',
  },
  {
    id: 'ap1b',
    document_id: 'doc1',
    requested_by: 'u1',
    requested_at: '2026-03-04T14:00:00Z',
    approver_id: 'u3',
    action: 'approve',
    actioned_at: '2026-03-04T16:00:00Z',
    step: 2,
    comment: '최종 승인합니다',
    metadata: { required_steps: 2, step_label: '대표 승인', step_role: 'admin' },
    created_at: '2026-03-04T14:00:00Z',
  },
  // doc2 (계약서) - 2단계 승인 완료
  {
    id: 'ap2',
    document_id: 'doc2',
    requested_by: 'u2',
    requested_at: '2026-03-10T10:00:00Z',
    approver_id: 'u1',
    action: 'approve',
    actioned_at: '2026-03-11T09:00:00Z',
    step: 1,
    comment: '계약 조건 확인됨',
    metadata: { required_steps: 2, step_label: '담당자 승인', step_role: 'manager' },
    created_at: '2026-03-10T10:00:00Z',
  },
  {
    id: 'ap2b',
    document_id: 'doc2',
    requested_by: 'u1',
    requested_at: '2026-03-11T09:00:00Z',
    approver_id: 'u3',
    action: 'approve',
    actioned_at: '2026-03-12T09:15:00Z',
    step: 2,
    comment: '발송 처리 바랍니다',
    metadata: { required_steps: 2, step_label: '대표 승인', step_role: 'admin' },
    created_at: '2026-03-11T09:00:00Z',
  },
  // doc3 (캠페인 기획안) - 1차 반려 후 재제출, 2단계 중 1단계 승인 완료 후 2단계 대기중
  {
    id: 'ap3',
    document_id: 'doc3',
    requested_by: 'u2',
    requested_at: '2026-03-16T09:00:00Z',
    approver_id: 'u1',
    action: 'reject',
    actioned_at: '2026-03-17T11:00:00Z',
    step: 1,
    comment: '타겟 연령대를 좀 더 구체적으로 작성해 주세요.',
    metadata: { required_steps: 2, step_label: '담당자 승인', step_role: 'manager' },
    created_at: '2026-03-16T09:00:00Z',
  },
  {
    id: 'ap4',
    document_id: 'doc3',
    requested_by: 'u2',
    requested_at: '2026-03-20T10:00:00Z',
    approver_id: 'u1',
    action: 'approve',
    actioned_at: '2026-03-20T15:00:00Z',
    step: 1,
    comment: null,
    metadata: { required_steps: 2, step_label: '담당자 승인', step_role: 'manager' },
    created_at: '2026-03-20T10:00:00Z',
  },
  {
    id: 'ap5',
    document_id: 'doc3',
    requested_by: 'u1',
    requested_at: '2026-03-20T15:00:00Z',
    approver_id: null,
    action: null,
    actioned_at: null,
    step: 2,
    comment: null,
    metadata: { required_steps: 2, step_label: '대표 승인', step_role: 'admin' },
    created_at: '2026-03-20T15:00:00Z',
  },
];

// ── 다단계 승인 진행 현황 (Mock) ─────────────────────────

export interface MockApprovalProgress {
  requiredSteps: number;
  completedSteps: number;
  currentStep: number | null;
  isFullyApproved: boolean;
  steps: { step: number; label: string | null; status: 'approved' | 'pending' | 'waiting' }[];
}

export const MOCK_APPROVAL_PROGRESS: Record<string, MockApprovalProgress> = {
  doc1: {
    requiredSteps: 2,
    completedSteps: 2,
    currentStep: null,
    isFullyApproved: true,
    steps: [
      { step: 1, label: '담당자 승인', status: 'approved' },
      { step: 2, label: '대표 승인', status: 'approved' },
    ],
  },
  doc2: {
    requiredSteps: 2,
    completedSteps: 2,
    currentStep: null,
    isFullyApproved: true,
    steps: [
      { step: 1, label: '담당자 승인', status: 'approved' },
      { step: 2, label: '대표 승인', status: 'approved' },
    ],
  },
  doc3: {
    requiredSteps: 2,
    completedSteps: 1,
    currentStep: 2,
    isFullyApproved: false,
    steps: [
      { step: 1, label: '담당자 승인', status: 'approved' },
      { step: 2, label: '대표 승인', status: 'pending' },
    ],
  },
  doc4: {
    requiredSteps: 2,
    completedSteps: 0,
    currentStep: null,
    isFullyApproved: false,
    steps: [
      { step: 1, label: '담당자 승인', status: 'waiting' },
      { step: 2, label: '대표 승인', status: 'waiting' },
    ],
  },
};

// ── 활동 로그 ────────────────────────────────────────────

export const MOCK_ACTIVITY_LOGS: (ActivityLog & { actor_name: string })[] = [
  {
    id: 'log1',
    organization_id: 'org1',
    entity_type: 'project',
    entity_id: 'p1',
    project_id: 'p1',
    action: 'create',
    actor_id: 'u2',
    actor_name: '이지현',
    description: '프로젝트를 생성했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-01T09:00:00Z',
  },
  {
    id: 'log2',
    organization_id: 'org1',
    entity_type: 'document',
    entity_id: 'doc1',
    project_id: 'p1',
    action: 'create',
    actor_id: 'u2',
    actor_name: '이지현',
    description: '견적서를 생성했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-03T10:00:00Z',
  },
  {
    id: 'log3',
    organization_id: 'org1',
    entity_type: 'document',
    entity_id: 'doc1',
    project_id: 'p1',
    action: 'approve',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '견적서를 승인했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-04T14:00:00Z',
  },
  {
    id: 'log4',
    organization_id: 'org1',
    entity_type: 'document',
    entity_id: 'doc1',
    project_id: 'p1',
    action: 'send',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '견적서를 고객에게 발송했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-05T14:30:00Z',
  },
  {
    id: 'log5',
    organization_id: 'org1',
    entity_type: 'project',
    entity_id: 'p1',
    project_id: 'p1',
    action: 'transition',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '상태를 "영업"에서 "견적 작성"으로 변경했습니다',
    old_data: { status: 'A_sales' },
    new_data: { status: 'B1_estimate_draft' },
    metadata: {},
    created_at: '2026-03-05T14:35:00Z',
  },
  {
    id: 'log6',
    organization_id: 'org1',
    entity_type: 'project',
    entity_id: 'p1',
    project_id: 'p1',
    action: 'transition',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '상태를 "견적 전달"에서 "입금 대기"로 변경했습니다',
    old_data: { status: 'B3_estimate_sent' },
    new_data: { status: 'D1_payment_pending' },
    metadata: {},
    created_at: '2026-03-10T16:00:00Z',
  },
  {
    id: 'log7',
    organization_id: 'org1',
    entity_type: 'project',
    entity_id: 'p1',
    project_id: 'p1',
    action: 'transition',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '상태를 "입금 대기"에서 "입금 확인"으로 변경했습니다',
    old_data: { status: 'D1_payment_pending' },
    new_data: { status: 'D2_payment_confirmed' },
    metadata: {},
    created_at: '2026-03-12T10:00:00Z',
  },
  {
    id: 'log8',
    organization_id: 'org1',
    entity_type: 'project',
    entity_id: 'p1',
    project_id: 'p1',
    action: 'transition',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '상태를 "입금 확인"에서 "집행"으로 변경했습니다',
    old_data: { status: 'D2_payment_confirmed' },
    new_data: { status: 'E4_execution' },
    metadata: {},
    created_at: '2026-03-15T09:00:00Z',
  },
  {
    id: 'log9',
    organization_id: 'org1',
    entity_type: 'document',
    entity_id: 'doc3',
    project_id: 'p1',
    action: 'reject',
    actor_id: 'u1',
    actor_name: '김민수',
    description: '캠페인 기획안을 반려했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-17T11:00:00Z',
  },
  {
    id: 'log10',
    organization_id: 'org1',
    entity_type: 'document',
    entity_id: 'doc3',
    project_id: 'p1',
    action: 'resubmit',
    actor_id: 'u2',
    actor_name: '이지현',
    description: '캠페인 기획안을 수정 후 재제출했습니다',
    old_data: null,
    new_data: null,
    metadata: {},
    created_at: '2026-03-20T10:00:00Z',
  },
];

// ── 프로젝트 (조합) ─────────────────────────────────────

export const MOCK_PROJECT: ProjectWithRelations = {
  id: 'p1',
  organization_id: 'org1',
  client_id: 'c1',
  title: '블루오션 3월 SNS 마케팅 대행',
  description: '인스타그램 + 네이버 블로그 통합 마케팅 대행. 장기 계약 진행.',
  code: 'PRJ-2026-0042',
  status: 'E4_execution',
  service_type: 'viral_performance',
  payment_type: 'deposit',
  owner_id: 'u2',
  start_date: '2026-03-15',
  end_date: '2026-05-31',
  total_amount: 3960000,
  currency: 'KRW',
  metadata: {},
  created_at: '2026-03-01T09:00:00Z',
  updated_at: '2026-03-15T09:00:00Z',
  client: MOCK_CLIENT,
  owner: MOCK_USERS.u2,
  documents: MOCK_DOCUMENTS,
};

// ── 현재 사용자 (로그인된 유저) ──────────────────────────

export const MOCK_CURRENT_USER = MOCK_USERS.u1;
